name: CI-CD Pipeline for Docker + Kubernetes (PetStore)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Backend
      - name: Build Backend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-petstore:latest ./backend

      # Build Frontend
      - name: Build Frontend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-petstore:latest ./frontend

      # Push Backend
      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-petstore:latest

      # Push Frontend
      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-petstore:latest
