name: CI-CD Pipeline for Docker + Kubernetes (PetStore)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Backend
      - name: Build Backend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-petstore:latest ./backend

      # Build Frontend
      - name: Build Frontend Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-petstore:latest ./frontend

      # Push Backend
      - name: Push Backend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-petstore:latest

      # Push Frontend
      - name: Push Frontend Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-petstore:latest


  deploy:
    name: Deploy to Docker Desktop Kubernetes
    runs-on: ubuntu-latest
    needs: build     # Only run after build is successful

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      # Configure kubeconfig from GitHub Secret
      - name: Set Kubernetes Config
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

      # Update backend YAML to use Docker Hub images
      - name: Update backend image name
        run: |
          sed -i "s|backend-petstore:latest|${{ secrets.DOCKER_USERNAME }}/backend-petstore:latest|g" k8s/backend-deployment.yaml

      # Update frontend YAML to use Docker Hub images
      - name: Update frontend image name
        run: |
          sed -i "s|frontend-petstore:latest|${{ secrets.DOCKER_USERNAME }}/frontend-petstore:latest|g" k8s/frontend-deployment.yaml

      # Apply Kubernetes manifests
      - name: Apply Kubernetes Resources
        run: |
          kubectl apply -f k8s/

      # Verify Pods
      - name: Show Pods After Deployment
        run: kubectl get pods -o wide

      # Verify Services
      - name: Show Services
        run: kubectl get svc
